---
title: "Kotal Kahn Rap"
---

Huītzilōpōchtli

Welcome to my Trial of Strength! So you better be prepared!

You draw powers from the Sun, am I supposed to be scared?!

I drink the blood of champions! Not those who lose the fight!

The second Kahn’s reign ends, burnt out in the sunlight!

After Shao was killed, you integrated Asian into Aztec, yet your authority’s not respected.

Your turned tail or betrayed you, how the hell did you not detect it?!

This blue fish must be out of water, ‘cause power is over his head.

Hey, K’uk’ulkan! You should grab him before this fish winds up dead!

Kotal Kahn

For all the mythologies, this Sun God spits least fire.

He’s fly like a hummingbird when he’s about to retire.

What a little bird can do against the Black Jaguar of Mortal Kombat?

No matter how poorly written I was, you’re the God that falls flat.

How weak am I when you’re the only War God who’s always on the run?

You were like that when you beheaded your sister then her children for fun.

You have worse sibling issues when you fight like Tom and Jerry.

Huītzilōpōchtli

Irrelevant, mortal?! You underestimate the mythologies you read.

“You can’t win a duel against Shao without losing your head.

You stole Shao’s crown, but challenging me’s your fatal mistake.

Now your heart and your head? They’re mine to take!

(HUAGH!)

Gather your Shokans and Takarans, your last allies in the fight,

But you’re just a pussy-ass bitch who can’t handle the light!

My army faced conquistadors, guns blazing and bold,

While your troops fall apart with discipline so cold.

All your feats are decanonned, lost in history's trash,

Like your claim to power, just a failure in a flash!

With your strength and Kombat, I barely give a FUCK!

I should’ve faced Shao Kahn. It’s official. YOU SUCK!!!

Kotal Kahn

With all the 
